### ISSUE TITLE
Not compatible with Angular 5

### ISSUE THREAD

**Issue by SlimDogs** [bmvantunes/angular-library-builder#181]
Hi Bruno !!! :)

When used with project which is based on Angular 5 I get this:

"Error: Metadata version mismatch for module ...@angular/core/core.d.ts, found version 4, expected 3"

Most likely it's one of you projects dependency requiring update (which may not be ready yet...). I will try to look into it myself when I will have time, just giving heads up :)

**Comment by SlimDogs** [comment]
Now when I looked into it - yup it's only up to you to approve Greenkeepers PR's and this should be fixed! :)

**Comment by bmvantunes** [comment]
Hello @SlimDogs .
Using this to build a "normal" angular cli 1.5 library with angular 5.0.0, it works.

Can you please send me your full log?

Thanks,
Bruno

**Comment by SlimDogs** [comment]
```> @maple-syrup-media/fe-app-retailer-page@0.0.3-20 inline:compile:universal /Users/tautvydasderzinskas/repos/fe-app-retailer-page
> angular-library-builder --rootDir src --outDir universal-dist --tsconfig ./universal/tsconfig-nglb-override.json

Error: Metadata version mismatch for module /Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/@angular/core/core.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.resolveSymbol (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:25206:14)
    at StaticReflector.findSymbolDeclaration (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:24393:67)
    at StaticReflector.findDeclaration (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:24377:21)
    at StaticReflector.initializeConversionMap (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:24595:36)
    at new StaticReflector (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:24337:14)
    at Object.createAotCompiler (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler/bundles/compiler.umd.js:25778:44)
    at Function.CodeGenerator.create (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler-cli/src/codegen.js:84:36)
    at codegen (/Users/tautvydasderzinskas/repos/fe-app-retailer-page/node_modules/angular-library-builder/node_modules/@angular/compiler-cli/src/main.js:13:36)
Compilation failed

Unfortunately we were not able to build your library! :(


npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "inline:compile:universal"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @maple-syrup-media/fe-app-retailer-page@0.0.3-20 inline:compile:universal: `angular-library-builder --rootDir src --outDir universal-dist --tsconfig ./universal/tsconfig-nglb-override.json`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @maple-syrup-media/fe-app-retailer-page@0.0.3-20 inline:compile:universal script 'angular-library-builder --rootDir src --outDir universal-dist --tsconfig ./universal/tsconfig-nglb-override.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @maple-syrup-media/fe-app-retailer-page package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     angular-library-builder --rootDir src --outDir universal-dist --tsconfig ./universal/tsconfig-nglb-override.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @maple-syrup-media/fe-app-retailer-page
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @maple-syrup-media/fe-app-retailer-page
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tautvydasderzinskas/repos/fe-app-retailer-page/npm-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:universal"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @maple-syrup-media/fe-app-retailer-page@0.0.3-20 build:universal: `npm run build:aot && npm run inline:compile:universal && npm run webpack:universal`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @maple-syrup-media/fe-app-retailer-page@0.0.3-20 build:universal script 'npm run build:aot && npm run inline:compile:universal && npm run webpack:universal'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @maple-syrup-media/fe-app-retailer-page package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:aot && npm run inline:compile:universal && npm run webpack:universal
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @maple-syrup-media/fe-app-retailer-page
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @maple-syrup-media/fe-app-retailer-page
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tautvydasderzinskas/repos/fe-app-retailer-page/npm-debug.log
Something went wrong building...Sorry!

npm WARN @maple-syrup-media/fe-components@1.0.35 requires a peer of @maple-syrup-media/fe-common-styles@>= 0.1.4 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/core@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/common@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.5 requires a peer of @angular/forms@^4.0.3 but none was installed.
npm WARN @angular/compiler-cli@5.0.0 requires a peer of typescript@>=2.4.2 <2.5 but none was installed.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of popper.js@^1.12.3 but none was installed.
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @maple-syrup-media/fe-app-retailer-page@0.0.3-20 prepublish: `node ./universal/universal.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @maple-syrup-media/fe-app-retailer-page@0.0.3-20 prepublish script 'node ./universal/universal.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @maple-syrup-media/fe-app-retailer-page package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./universal/universal.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @maple-syrup-media/fe-app-retailer-page
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @maple-syrup-media/fe-app-retailer-page
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tautvydasderzinskas/repos/fe-app-retailer-page/npm-debug.log```

My package.json:
```
{
  "name": "@maple-syrup-media/fe-app-retailer-page",
  "version": "0.0.3-20",
  "description": "Refactored and SEO optimized retailer page",
  "repository": {
    "type": "git",
    "url": "git@bitbucket.org:maplesyrupgroup/fe-app-retailer-page.git"
  },
  "license": "UNLICENSED",
  "files": [
    "dist",
    "README.md"
  ],
  "scripts": {
    "start": "ng serve --open --port 3200",
    "test": "ng test --code-coverage",
    "test:ci": "npm test -- --single-run --browsers Electron",
    "lint": "ng lint --type-check",
    "build:aot": "ng build --prod --aot --output-hashing=false",
    "inline:compile:universal": "angular-library-builder --rootDir src --outDir universal-dist --tsconfig ./universal/tsconfig-nglb-override.json",
    "webpack:universal": "webpack -p --config ./universal/universal.webpack.config.js",
    "prebuild:universal": "node ./universal/helpers/universal.before-run.js",
    "build:universal": "npm run build:aot && npm run inline:compile:universal && npm run webpack:universal",
    "prepublish": "node ./universal/universal.js",
    "test:universal:prod": "npm run prepublish && lite-server --baseDir dist",
    "bundle-report": "webpack-bundle-analyzer dist/stats.json",
    "cleanInstall": "rm -rf node_modules && rm -rf package-lock.json && npm install",
    "prespeedreport": "npm run prepublish",
    "speedreport": "concurrently \"http-server ./dist -s -p 3000\" \"node tools/page-speed.js\""
  },
  "dependencies": {
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "@maple-syrup-media/fe-analytics": "0.3.8",
    "@maple-syrup-media/fe-components": "1.0.35",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "core-js": "2.5.1",
    "normalize.css": "7.0.0",
    "rxjs": "5.5.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/animations": "5.0.0",
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/platform-server": "5.0.0",
    "@ngtools/webpack": "1.8.0",
    "@types/jasmine": "2.6.3",
    "@types/node": "8.0.50",
    "angular-library-builder": "1.6.3",
    "bootstrap": "4.0.0-beta.2",
    "cheerio": "1.0.0-rc.2",
    "codelyzer": "4.0.1",
    "concurrently": "3.5.0",
    "electron": "1.7.9",
    "http-server": "0.10.0",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-electron": "5.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-mocha-reporter": "2.2.5",
    "lite-server": "2.3.0",
    "ngrok": "2.2.23",
    "protractor": "5.2.0",
    "psi": "3.0.0",
    "replace": "0.3.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0",
    "typescript": "2.6.1",
    "webpack": "3.8.1",
    "webpack-bundle-analyzer": "2.9.0"
  }
}
```

**Comment by SlimDogs** [comment]
Looks like it could be `ng-bootstrap` dependency which doesn't play well with Angular 5.0.0 in this context, but the error is not very informative...

**Comment by bmvantunes** [comment]
Hi @SlimDogs ,

You are completely right. They have version 4 in their package.json as dependency, which will install version 4 as well as version 5 in your project.

```"dependencies": {
    "@angular/core": "4.0.3",
    "@angular/common": "4.0.3",
    "@angular/forms": "4.0.3"
  },```

You should open an issue in ng-bootstrap for that. Ask them to transform dependencies into peerDependencies.

I will close this issue here, but if without ng-bootstrap you still got the error, please re-open :)
